# Generated by Django 5.0.6 on 2024-06-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantiry',
            new_name='quantity',
        ),
    ]
